### PR TITLE
Create an actix-web example of logging a query.

### PR DESCRIPTION
**Pull request by MidasLamb**
Added an example in the actix-web examples to demonstrate how to log an
entire query, in case an error is returned.

### CODE REVIEW

**Comment by sunli829** [comment]
Why don't you use the `extensions ::Logger`? 🙂

**Comment by MidasLamb** [comment]
As far as I could tell, it doesn't log the entire query, it only logs the path and the error itself, but e.g. input parameters and such are gone. I also didn't find a way to modify the extension to log the entire query as the Trait doesn't allow the error method access to the query source

**Comment by sunli829** [comment]
I updated `Extension::Logger` and now also provides query source when an error occurs, it was released in `v1.15.8`.
So you don't have to log errors yourself? 😀

**Comment by MidasLamb** [comment]
Wow, that's great! I took a quick look and I thought it wouldn't be straightforward to do in the logger, but I love that you guys just immediatly take an opportunity to improve the project without much hassle or anything. Keep up the good work!

**Comment by sunli829** [comment]
If there are any desired improvements, please feel free to let us know. 😄

**Pull request closed without merging**
